const Event = VueTables.Event; // import eventbus
Vue.use(VueTables.ClientTable);

new Vue({
  el: "#app",
  methods: {
    applyFilter(category) {
      console.log(this.selectedCategory);
      if (this.selectedCategory == '選択してください') {
        this.selectedCategory = '';
      }
      Event.$emit('vue-tables.filter::tags', this.selectedCategory);
    }
},
data: {
  columns: [
    'genre',
    'grade',
    // 'score',
    'title',
    'url',
    'tokyo',
    'osaka',
  ],
  books: getBooks(),
    categories: ['選択してください', 'CS基礎', 'プログラミング', '言語', 'DB', 'SQL', '設計・アーキテクチャ', 'テスト・品質', '運用', 'メンテナンス', 'セキュリティ', 'UI', 'UX', 'マーケティング', 'リスティング広告', '組織強化', '育成', 'マインド', '経営戦略', 'ヒューマンスキル', '分析・課題解決', 'プレゼンテーション', 'タスクマネジメント', 'パフォーマンス', 'Unix', 'OS', 'Web', 'HTTP', 'Mail', 'データ構造', 'アルゴリズム', 'ネットワーク', '文字コード', '言語処理', 'フレームワーク', 'PM', 'アジャイル', 'DevOps'],
    selectedCategory: '選択してください',
    options: {
	    filterByColumn: true, 
      listColumns: {
        genre: [
          {id: '技術', text: '技術'},
          {id: 'マネジメント', text: 'マネジメント'},
          {id: 'ビジネス', text: 'ビジネス'}
        ],
        grade: [
          {id: '初級', text: '初級'},
          {id: '中級', text: '中級'},
          {id: '上級', text: '上級'}
        ],
        tokyo: [
          {id: '〇', text: '〇'}
        ],
        osaka: [
          {id: '〇', text: '〇'}
        ],
      },
      headings: {
        'genre' : 'カテゴリ',
        'grade' : '対象',
        'title' : 'タイトル',
        'url' : 'URL',
        'tokyo' : '東京本棚',
        'osaka' : '大阪本棚',
      },
      // sortable: [ 'grede' ],
      filterable: ['genre', 'grade', 'title', 'tokyo', 'osaka'],
      // texts: {
      //   filterPlaceholder: '検索する'
      // },
      // orderBy: { ascending:true, column:'score' },
      perPage: 50,
      pagination: { chunk:50 },
      customFilters: [{
        name: 'tags',
        callback: function(row, query) {
          // console.log(row.tags + ":" + query);
          // console.log(row.tags.split(',').indexOf(query) >= 0);
          return row.tags.split(',').indexOf(query) >= 0;
        }
      }]
    }
  }
});

function getBooks() {
  return [
    { 'genre':'技術', 'grade' : '初級', 'title' : 'リーダブルコード', 'score' : '21', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4873115655', 'tags' : ',プログラミング,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '体系的に学ぶ 安全なWebアプリケーションの作り方 第2版', 'score' : '19', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B07DVY4H3M', 'tags' : 'CS基礎,,,,,,,,,セキュリティ,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'Webを支える技術', 'score' : '18', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4774142042', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,,,Web,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'SQLアンチパターン', 'score' : '17', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4873115892', 'tags' : ',,,DB,SQL,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'ノンデザイナーズ・デザインブック', 'score' : '14', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B01LW2P4CP/', 'tags' : ',,,,,,,,,,UI,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'Effective Java ', 'score' : '14', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4621303252/', 'tags' : ',プログラミング,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '内部構造から学ぶPostgreSQL 設計・運用計画の鉄則', 'score' : '13', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp//dp/4297100894/', 'tags' : ',,,DB,,設計・アーキテクチャ,,運用,,,,,,,,,,,,,,,パフォーマンス,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'Java言語で学ぶデザインパターン入門', 'score' : '12', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4797327030', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'Web API The Good Parts', 'score' : '12', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4873116864', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'マスタリングTCP/IP 入門編', 'score' : '11', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4274068765', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,ネットワーク,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'はじめて学ぶ　ソフトウェアのテスト技法', 'score' : '11', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B00HE8082Q', 'tags' : 'CS基礎,,,,,,テスト・品質,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'Linux教科書 LPICレベル1', 'score' : '10', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4798160490', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,Unix,OS,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '新装版 達人プログラマー 職人から名匠への道', 'score' : '10', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B06W567M44', 'tags' : ',プログラミング,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '現場で役立つシステム設計の原則 〜変更を楽で安全にするオブジェクト指向の実践技法', 'score' : '9', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B073GSDBGT', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '3分間HTTP&メールプロトコル基礎講座', 'score' : '8', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4774140813', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,,,Web,HTTP,Mail,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '文字コード超研究', 'score' : '8', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4899772939', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,文字コード,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'テスト駆動開発', 'score' : '8', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4274217884/', 'tags' : ',,,,,,テスト・品質,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '暗号技術入門 第3版　秘密の国のアリス', 'score' : '7', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B015643CPE', 'tags' : 'CS基礎,,,,,,,,,セキュリティ,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'リファクタリング―既存のコードを安全に改善する―', 'score' : '6', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B01IGW5MG0', 'tags' : ',プログラミング,,,,設計・アーキテクチャ,,,メンテナンス,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'レガシーコード改善ガイド', 'score' : '6', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4798116831', 'tags' : ',プログラミング,,,,設計・アーキテクチャ,,,メンテナンス,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '情報処理教科書 データベーススペシャリスト ', 'score' : '6', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B07G319LVC', 'tags' : ',,,DB,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'LEAN UX ', 'score' : '6', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873118050/', 'tags' : ',,,,,,,,,,,UX,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '知識ゼロから学ぶソフトウェアテスト', 'score' : '6', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B00HQ7S5CA', 'tags' : 'CS基礎,,,,,,テスト・品質,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'UNIXという考え方―その設計思想と哲学', 'score' : '5', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4274064069', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,マインド,,,,,,,Unix,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'オブジェクト脳のつくり方―Java・UML・EJBをマスターするための究極の基礎講座', 'score' : '5', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4798104183', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'マイクロサービスアーキテクチャ', 'score' : '5', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4873117607', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '達人に学ぶDB設計 徹底指南書', 'score' : '5', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B00EE1XPAI', 'tags' : ',,,DB,SQL,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'デザイン入門教室', 'score' : '4', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B010CQDQMK/', 'tags' : ',,,,,,,,,,UI,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'はじめてのUIデザイン', 'score' : '4', 'tokyo' : '', 'osaka' : '', 'url' : 'https://peaks.cc/books/ui_design', 'tags' : ',,,,,,,,,,UI,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'UIデザイン　みんなで考え、カイゼンする。', 'score' : '4', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B07PQF8TBW/', 'tags' : ',,,,,,,,,,UI,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '情報アーキテクチャ', 'score' : '4', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873117720/', 'tags' : ',,,,,,,,,,UI,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'はじめてのカスタマージャーニーマップワークショップ', 'score' : '4', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4798153753', 'tags' : ',,,,,,,,,,,UX,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '初めてのPHP', 'score' : '4', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4873117933', 'tags' : ',プログラミング,言語,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'オラクル認定資格教科書 Javaプログラマ Silver', 'score' : '4', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B01BLCJ984', 'tags' : ',プログラミング,言語,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '入門UNIXシェルプログラミング―シェルの基礎から学ぶUNIXの世界', 'score' : '4', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4797321946', 'tags' : ',プログラミング,言語,,,,,,,,,,,,,,,,,,,,,Unix,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'デザインパターンとともに学ぶオブジェクト指向のこころ', 'score' : '4', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4621066048', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '上級', 'title' : 'エリック・エヴァンスのドメイン駆動設計', 'score' : '4', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B00GRKD6XU', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'Design Systems ―デジタルプロダクトのためのデザインシステム実践ガイド', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4862464122', 'tags' : ',,,,,,,,,,UI,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'UXリサーチの道具箱', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4274222187', 'tags' : ',,,,,,,,,,,UX,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '人間中心設計の基礎', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4764904438', 'tags' : ',,,,,,,,,,,UX,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'マッピングエクスペリエンス ―カスタマージャーニー、サービスブループリント、その他ダイアグラムから価値を創る', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/487311800X', 'tags' : ',,,,,,,,,,,UX,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'インタフェースデザインの心理学 ―ウェブやアプリに新たな視点をもたらす100の指針', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873115574', 'tags' : ',,,,,,,,,,,UX,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '入門 ウェブ分析論', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4797368845/', 'tags' : ',,,,,,,,,,,,,,,,,,,分析・課題解決,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'プログラマが知るべき97のこと', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873114799', 'tags' : ',,,,,設計・アーキテクチャ,テスト・品質,,,,,,,,,,マインド,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'プリンシプル オブ プログラミング', 'score' : '3', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B071V7MY82', 'tags' : ',プログラミング,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '基礎から学ぶ Vue.js ', 'score' : '3', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4863542453', 'tags' : ',プログラミング,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,フレームワーク,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'Swift 実践入門', 'score' : '3', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/477419414X', 'tags' : ',プログラミング,言語,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'ios ** プログラミング', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://peaks.cc/iOS12', 'tags' : ',プログラミング,言語,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'iOSアプリ設計パターン入門', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://peaks.cc/books/iOS_architecture', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'Android アプリ設計パターン入門', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://peaks.cc/books/architecture_patterns', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'おうちで学べるデータベースのきほん', 'score' : '3', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B00TTRZFDC', 'tags' : ',,,DB,SQL,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '失敗から学ぶRDBの正しい歩き方', 'score' : '3', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B07P8PMHLL', 'tags' : ',,,DB,SQL,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'なるほどデザイン ', 'score' : '3', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4844365177/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,デザイン' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '「伝わる」印刷物の基本ルール', 'score' : '3', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4416616597/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,デザイン' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'DTP基礎', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4844364766/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,デザイン' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'デザイン入門教室[特別講義] 確かな力を身に付けられる ', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/479735142X/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'プログラミング作法', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4756136494/', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '入門 コンピュータ科学 ITを支える技術と理論の基礎知識', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4048930540/', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'ユーザーストーリーマッピング', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873117321', 'tags' : ',,,,,,,,,,,UX,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'アルゴリズム図鑑 絵で見てわかる26のアルゴリズム', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B07179Q3MJ', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,,,,,,データ構造,アルゴリズム,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '入門監視', 'score' : '2', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4873118646', 'tags' : ',,,,,,,運用,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'Real World HTTP', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873118042', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,,,,HTTP,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '自然言語処理の基本と技術', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B01CGAPLLO', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,言語処理,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '開眼! JavaScript ―言語仕様から学ぶJavaScriptの本質', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/487311621X', 'tags' : ',プログラミング,言語,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '進化的アーキテクチャ ―絶え間ない変化を支える', 'score' : '2', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873118565', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '上級', 'title' : '実践ドメイン駆動設計', 'score' : '2', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/479813161X/', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'Webディレクションの新・標準ルール', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4844366467/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '知りたいレイアウトデザイン', 'score' : '2', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4774194182/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,デザイン' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '知りたい　タイポグラフィ　デザイン ', 'score' : '2', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4774195227/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,デザイン' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'あるあるデザイン', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4844368427/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,デザイン' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'リスティング広告のやさしい教科書', 'score' : '2', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/484436765X/', 'tags' : ',,,,,,,,,,,,,リスティング広告,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '新版 リスティング広告－成功の法則－', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4881669788/', 'tags' : ',,,,,,,,,,,,,リスティング広告,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'リスティング広告 プロの思考回路 (WEB PROFESSIONAL)', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4048703609/', 'tags' : ',,,,,,,,,,,,,リスティング広告,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '新版 SEM:リスティング広告 Googleアドワーズ&Yahoo!リスティング広告対応 Web担当者が身につけておくべき新・100の法則。', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4844332694/', 'tags' : ',,,,,,,,,,,,,リスティング広告,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'レガシーソフトウェア改善ガイド', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B01MSLAFPT/', 'tags' : ',,,,,,,,メンテナンス,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'プログラマのための文字コード技術入門', 'score' : '1', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/477414164X', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,文字コード,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'Vue.js 入門', 'score' : '1', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4297100916', 'tags' : ',プログラミング,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,フレームワーク,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'Clean Architecture 達人に学ぶソフトウェアの構造と設計', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B07FSBHS2V', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '上級', 'title' : '情報処理教科書 システムアーキテクト', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B07MXG9MK9', 'tags' : ',,,,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'シンプリシティの法則', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4492556079/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,デザイン' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'ロゴデザインのロジック ', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4866730285/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,デザイン' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '最速で成果を出すリスティング広告の教科書', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/477417257X/', 'tags' : ',,,,,,,,,,,,,リスティング広告,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '実践 インハウス・リスティング広告', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4844334379/', 'tags' : ',,,,,,,,,,,,,リスティング広告,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'ネット広告ハンドブック', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/482074836X/', 'tags' : ',,,,,,,,,,,,,リスティング広告,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '実践 インハウス・リスティング広告 「丸投げ体質」から脱却するSEM成功の新条件 ', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4844334379/', 'tags' : ',,,,,,,,,,,,,リスティング広告,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'ソフトウェアテスト293の鉄則', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/482228154X/', 'tags' : ',,,,,,テスト・品質,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'みんなのコンピュータサイエンス', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4798154814/', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'たのしいUNIX', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4756107850', 'tags' : 'CS基礎,,,,,,,,,,,,,,,,,,,,,,,Unix,OS,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'ハッカーになろう', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://cruel.org/freeware/hacker.html', 'tags' : ',,,,,,,,,,,,,,,,マインド,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '伽藍とバザール', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://cruel.org/freeware/cathedral.html', 'tags' : ',,,,,,,,,,,,,,,,マインド,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'やさしいJava', 'score' : '0', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4815600848', 'tags' : ',プログラミング,言語,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : 'iPhoneアプリ開発講座 はじめてのSwift', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4797385286', 'tags' : ',プログラミング,言語,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '初級', 'title' : '入門 Python 3', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873117380/', 'tags' : ',プログラミング,言語,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : '実践的データモデリング入門 ', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4798103853', 'tags' : ',,,DB,,設計・アーキテクチャ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'技術', 'grade' : '中級', 'title' : 'Androidテスト全書', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://peaks.cc/books/android_testing', 'tags' : ',,,,,,テスト・品質,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : 'カイゼン・ジャーニー たった1人からはじめて、「越境」するチームをつくるまで', 'score' : '19', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4798153346', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,アジャイル,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : 'Team Geek ―Googleのギークたちはいかにしてチームを作るのか', 'score' : '13', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4873116309', 'tags' : ',,,,,,,,,,,,,,組織強化,,マインド,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : 'SCRUM BOOT CAMP THE BOOK', 'score' : '11', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4798129712', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,アジャイル,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : 'エンジニアリング組織論への招待', 'score' : '10', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B079TLW41L', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : 'エンジニアのためのマネジメントキャリアパス ', 'score' : '9', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873118484', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'アジャイルサムライ', 'score' : '8', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4274068560', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'ピープルウエア', 'score' : '7', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B00I96CJWO', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'リーン開発の本質', 'score' : '7', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/482228350X/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'プロジェクトマネジメント標準 PMBOK入門', 'score' : '6', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4274066150', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'エラスティックリーダーシップ ―自己組織化チームの育て方', 'score' : '6', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873118026', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'スモール・リーダーシップ チームを育てながらゴールに導く「協調型」リーダー', 'score' : '6', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B074PM7VF5', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'エッセンシャル スクラム: アジャイル開発に関わるすべての人のための完全攻略ガイド', 'score' : '5', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4798130508/', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,アジャイル,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : 'Fearless Change アジャイルに効く アイデアを組織に広めるための48のパターン', 'score' : '5', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B07QZC41ZQ', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'ザ・ゴール', 'score' : '4', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4478420408', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'デザイン組織のつくりかた　デザイン思考を駆動させるインハウスチームの構築＆運用ガイド', 'score' : '4', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4802510837', 'tags' : ',,,,,,,,,,UI,UX,,,組織強化,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : '情報処理教科書 プロジェクトマネージャ', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4798158143', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '上級', 'title' : 'PMP試験合格虎の巻 第6版対応', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4865751211', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'the phoenix project', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4822285359', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,アジャイル,DevOps,デザイン' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'スクラム現場ガイド', 'score' : '3', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4839951993', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,アジャイル,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : '行動科学を使ってできる人が育つ! 教える技術', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4761267550', 'tags' : ',,,,,,,,,,,,,,,育成,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : 'リーダーのための! コーチングスキル', 'score' : '3', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4799105531', 'tags' : ',,,,,,,,,,,,,,,育成,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'ヤフーの1on1―――部下を成長させるコミュニケーションの技法', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4478069786', 'tags' : ',,,,,,,,,,,,,,,育成,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : '情熱プログラマー ソフトウェア開発者の幸せな生き方', 'score' : '3', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B01IGW5MQ0', 'tags' : ',,,,,,,,,,,,,,組織強化,,マインド,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'OKR(オーケーアール) シリコンバレー式で大胆な目標を達成する方法', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B07B2R1ZDL', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'ゆとりの法則 － 誰も書かなかったプロジェクト管理の誤解', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4822281116/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : '熊とワルツを', 'score' : '2', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4822281868', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : 'コーチングの基本 ', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4534056591/', 'tags' : ',,,,,,,,,,,,,,,育成,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'アドレナリンジャンキー プロジェクトの現在と未来を映す86パターン', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4822284018/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : '人と組織を効果的に動かす KPIマネジメント', 'score' : '1', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4799106104', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : 'デッドライン', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4822280535/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '初級', 'title' : 'すべては「前向き質問」でうまくいく', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4799316230', 'tags' : ',,,,,,,,,,,,,,,育成,マインド,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : '「経験学習」入門 ', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4478017298', 'tags' : ',,,,,,,,,,,,,,,育成,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '中級', 'title' : '人月の神話【新装版】', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4621066080/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'マネジメント', 'grade' : '上級', 'title' : 'ユーザー企業ソフトウェアメトリックス調査2019 システム開発・保守調査 ~システム開発・保守の実績プロジェクトデータを元に分析', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4903477517/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'マネジメント', 'grade' : '上級', 'title' : 'ユーザー企業 ソフトウェアメトリックス調査2019 システム運用調査 ~運用コストの内訳と管理指標に関する調査・分析~', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4903477525/', 'tags' : ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'ライト、ついてますか―問題発見の人間学', 'score' : '10', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4320023684/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,分析・課題解決,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '1分で話せ 世界のトップが絶賛した大事なことだけシンプルに伝える技術', 'score' : '9', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4797395230', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'なぜ、あなたの仕事は終わらないのか スピードは最強の武器である', 'score' : '8', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B01GPCKJWK/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,タスクマネジメント,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'ファシリテーションの教科書―組織を活性化させるコミュニケーションとリーダーシップ', 'score' : '7', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4492533486', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '人を動かす', 'score' : '6', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/442210098X/', 'tags' : ',,,,,,,,,,,,,,,,マインド,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '99%の人がしていない たった1%のリーダーのコツ', 'score' : '6', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B00DAULFEW', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '中級', 'title' : '問題解決 ― あらゆる課題を突破する ビジネスパーソン必須の仕事術', 'score' : '6', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B00N0XOKZU/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,分析・課題解決,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '99％の人がしていないたった1％の仕事のコツ', 'score' : '5', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B009SKNUO6', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'エンジニアのための図解思考　再入門', 'score' : '5', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B00EESW7OG', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,分析・課題解決,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'マンガでわかる トヨタ流の生産方式とマネジメント', 'score' : '4', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4839960054', 'tags' : ',,,,,,,,,,,,,,組織強化,,,,ヒューマンスキル,,,,,,,,,,,,,,,,PM,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '誰のためのデザイン？　増補・改訂版　―認知科学者のデザイン原論', 'score' : '4', 'tokyo' : '〇', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4788514346', 'tags' : ',,,,,,,,,,UI,UX,,,,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '思考の整理学 ', 'score' : '4', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4480020470/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,分析・課題解決,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '分かりやすい表現の技術', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4062572451', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,プレゼンテーション,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '分かりやすい説明の技術', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4062573873', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,プレゼンテーション,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '分かりやすい文章の技術', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4062574438', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,プレゼンテーション,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '神・時間術', 'score' : '3', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4479795820/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,タスクマネジメント,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '伝え方が9割', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B00BHCM7HE', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'あなたが上司から求められているシンプルな50のこと', 'score' : '3', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4788910519/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '中級', 'title' : 'みんなではじめるデザイン批評―目的達成のためのコラボレーション&コミュニケーション改善ガイド', 'score' : '3', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B01J2OEYLU/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '上級', 'title' : 'モチベーション3.0 持続する「やる気!」をいかに引き出すか ', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4062816199/', 'tags' : ',,,,,,,,,,,,,,,育成,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'マーケティングの基本', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4534056095/', 'tags' : ',,,,,,,,,,,,マーケティング,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'ザ・マイクロコピー ', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4798049247/', 'tags' : ',,,,,,,,,,,,マーケティング,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'グロービスMBA集中講義 ［実況］ロジカルシンキング教室', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B00IJ18JGY', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,分析・課題解決,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'すぐやる！　「行動力」を高める“科学的な”方法', 'score' : '2', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/B01J5OH1WG', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,タスクマネジメント,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '入社1年目の教科書', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4478015422/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '中級', 'title' : '完訳 7つの習慣 人格主義の回復', 'score' : '2', 'tokyo' : '', 'osaka' : '〇', 'url' : 'https://www.amazon.co.jp/dp/4863940246', 'tags' : ',,,,,,,,,,,,,,,育成,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '中級', 'title' : 'イシューからはじめよ――知的生産の「シンプルな本質」', 'score' : '2', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4862760856/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,分析・課題解決,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '毎日読みたい365日の広告コピー', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4909044094/', 'tags' : ',,,,,,,,,,,,マーケティング,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '中級', 'title' : 'キャズム Ver.2 増補改訂版 新商品をブレイクさせる「超」マーケティング理論', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B00OCGT0HM', 'tags' : ',,,,,,,,,,,,マーケティング,,,,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '上級', 'title' : '情報処理教科書 ITストラテジスト', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B07N19LL58', 'tags' : ',,,,,,,,,,,,,,,,,経営戦略,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'データ・統計分析ができる本', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4534050720/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,分析・課題解決,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '世界一やさしい問題解決の授業 ', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4478000492/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,分析・課題解決,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '考具 ', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4484032058/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,分析・課題解決,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '中級', 'title' : 'デザインの伝え方', 'score' : '1', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4873117798', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '上級', 'title' : '仕事は楽しいかね？', 'score' : '1', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/B00SIM19YS', 'tags' : ',,,,,,,,,,,,,,,育成,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '上級', 'title' : '動機づける力―モチベーションの理論と実践', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4478011540', 'tags' : ',,,,,,,,,,,,,,,育成,,,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '上級', 'title' : 'この1冊ですべてわかる 経営戦略の基本', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4534044674', 'tags' : ',,,,,,,,,,,,マーケティング,,,,,経営戦略,,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '社内プレゼンの資料作成術', 'score' : '0', 'tokyo' : '〇', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4478061521/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,プレゼンテーション,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '社外プレゼンの資料作成術', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4478068267/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,プレゼンテーション,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '自分の小さな「箱」から脱出する方法', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4479791779', 'tags' : ',,,,,,,,,,,,,,,,マインド,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : '学びを結果に変えるアウトプット大全', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4801400558/', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'たった一言で人生が変わるほめ言葉の魔法', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4776209292', 'tags' : ',,,,,,,,,,,,,,,育成,,,ヒューマンスキル,,,,,,,,,,,,,,,,,,,' },
    { 'genre':'ビジネス', 'grade' : '初級', 'title' : 'なぜなぜ分析10則―真の論理力を鍛える', 'score' : '0', 'tokyo' : '', 'osaka' : '', 'url' : 'https://www.amazon.co.jp/dp/4817193026', 'tags' : ',,,,,,,,,,,,,,,,,,ヒューマンスキル,分析・課題解決,,,,,,,,,,,,,,,,,,' }    
  ];
}
